MODEL_BERT_BASE_MULTILINGUAL = 'bert-base-multilingual-cased'
# MODEL_BERT_LARGE_MULTILINGUAL = 'bert-large-multilingual-cased'
MODEL_XLM_ROBERTA_BASE = 'xlm-roberta-base'
MODEL_XLM_ROBERTA_LARGE = 'xlm-roberta-large'

AVAILABLE_MODELS = [
    MODEL_BERT_BASE_MULTILINGUAL,
    # MODEL_BERT_LARGE_MULTILINGUAL,
    MODEL_XLM_ROBERTA_BASE,
    MODEL_XLM_ROBERTA_LARGE,
]